(() => {
const D=window.RADAR_DATA;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={route:'today',params:[],watch:new Set(JSON.parse(localStorage.getItem('radar-watch')||'[]')),marketFilter:'all',productMarket:'all',productForm:'all',regCountry:'all',oppCountry:'all',compare:new Set(['PT','DE','DK'])};
const icons={today:'◆',markets:'◫',companies:'◉',products:'◇',regulation:'§',opportunities:'↗',compare:'⇄',watchlist:'★',methodology:'✓',search:'⌕'};
const routes=[
  ['today','Today'],['markets','Markets'],['companies','Companies'],['products','Products'],['regulation','Regulation'],['opportunities','Opportunities'],['compare','Compare'],['watchlist','Watchlist']
];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function source(id){return D.sources[id]||null}
function saveWatch(){localStorage.setItem('radar-watch',JSON.stringify([...state.watch]));renderNavCounts()}
function watchKey(type,id){return `${type}:${id}`}
function isWatched(type,id){return state.watch.has(watchKey(type,id))}
function toggleWatch(type,id,label){const k=watchKey(type,id);if(state.watch.has(k)){state.watch.delete(k);toast(`${label} removed from watchlist`)}else{state.watch.add(k);toast(`${label} added to watchlist`)}saveWatch();render()}
function toast(msg){const r=$('#toastRegion');const t=document.createElement('div');t.className='toast';t.textContent=msg;r.appendChild(t);setTimeout(()=>t.remove(),2600)}
function badge(text,cls=''){return `<span class="badge ${cls}">${esc(text)}</span>`}
function sourceButton(id,label='View source'){const s=source(id);if(!s)return'';return `<button class="btn ghost" data-source="${esc(id)}">${esc(label)}</button>`}
function watchButton(type,id,label){return `<button class="btn ${isWatched(type,id)?'saved':''}" data-watch-type="${esc(type)}" data-watch-id="${esc(id)}" data-watch-label="${esc(label)}">${isWatched(type,id)?'★ Watching':'☆ Watch'}</button>`}
function nav(){return `
  <div class="brand"><div class="brand-mark">R</div><div><div class="brand-name">Intelligence Radar</div><div class="brand-sub">Medicinal cannabis · Europe</div></div><button class="sidebar-x" data-close-nav aria-label="Close menu">×</button></div>
  <div class="nav-section"><div class="nav-label">Workspace</div>
    ${routes.slice(0,1).map(([r,l])=>navItem(r,l)).join('')}
    <a class="nav-item" href="#search" data-open-search><span class="nav-icon">${icons.search}</span>Search everything<span class="nav-badge">/</span></a>
  </div>
  <div class="nav-section"><div class="nav-label">Intelligence</div>${routes.slice(1,6).map(([r,l])=>navItem(r,l)).join('')}</div>
  <div class="nav-section"><div class="nav-label">Analysis</div>${routes.slice(6).map(([r,l])=>navItem(r,l)).join('')} ${navItem('methodology','Evidence')}</div>
  <div class="sidebar-footer">${D.meta.observations.toLocaleString()} observations · ${D.meta.variablesReady}/${D.meta.variablesTotal} variables<br>Primary-first evidence policy</div>`}
function navItem(r,l){const active=state.route===r||state.route===r.slice(0,-1);return `<a class="nav-item ${active?'active':''}" href="#${r}"><span class="nav-icon">${icons[r]||'•'}</span>${l}${r==='watchlist'?`<span class="nav-badge" id="watchCount">${state.watch.size}</span>`:''}</a>`}
function mobileNav(){return ['today','markets','search','watchlist','opportunities'].map(r=>r==='search'?`<a class="mobile-link" href="#search" data-open-search><span>${icons.search}</span><span>Search</span></a>`:`<a class="mobile-link ${state.route===r?'active':''}" href="#${r}"><span>${icons[r]}</span><span>${r==='opportunities'?'Deals':r[0].toUpperCase()+r.slice(1)}</span></a>`).join('')}
function topbar(){return `<button class="menu-btn" id="menuBtn" aria-label="Open menu">☰</button><button class="search-trigger" data-open-search><span>⌕</span><span>Search market, company, product, law or opportunity…</span><span class="key">/</span></button><div class="topbar-actions"><div class="top-pill"><span class="live-dot"></span>${D.meta.updatedLabel}</div><a class="icon-btn" href="#watchlist" title="Watchlist">★</a></div>`}
function renderShell(){
  $('#sidebar').innerHTML=nav(); $('#mobileNav').innerHTML=mobileNav(); $('#topbar').innerHTML=topbar(); renderNavCounts();
}
function renderNavCounts(){const w=$('#watchCount');if(w)w.textContent=state.watch.size}
function head(eyebrow,title,copy){return `<div class="page-head"><div><div class="eyebrow">${esc(eyebrow)}</div><h1>${esc(title)}</h1><p class="page-copy">${esc(copy)}</p></div><div class="asof"><b>${D.meta.updatedLabel}</b>Current public preview</div></div>`}
function sectionHead(title,copy='',link='',label='View all'){return `<div class="section-head"><div><h2>${esc(title)}</h2>${copy?`<p>${esc(copy)}</p>`:''}</div>${link?`<a class="section-link" href="${link}">${esc(label)} →</a>`:''}</div>`}
function entityMeta(item){return `${item.country||item.region||''}${item.date?' · '+item.date:''}`}
function storyCard(i){return `<article class="story-card searchable" data-route="${esc(i.route||'today')}"><div class="meta-row">${badge(i.category,i.category==='Regulation'?'regulation':i.category==='Companies'?'company':'') }<span>${esc(entityMeta(i))}</span></div><h3>${esc(i.title)}</h3><p>${esc(i.summary)}</p><div class="why-line"><b>Why it matters:</b> ${esc(i.impact)}</div><div class="story-foot"><span>${esc(i.age||'')}</span><span>${source(i.source)?esc(source(i.source).name):''}</span></div></article>`}
function todayView(){
 const top=D.today[0], rest=D.today.slice(1,4);
 return `${head('Today','Your 5-minute cannabis brief','Only material changes, connected to the market, company, regulation and commercial context behind them.')}
 <div class="hero-grid"><article class="feature-card searchable"><div class="meta-row">${badge('Need to know')}${badge('Official','official')}<span>${esc(top.country)} · ${esc(top.age)}</span></div><h2>${esc(top.title)}</h2><p>${esc(top.summary)}</p><div class="impact-box"><b>Decision read-through:</b> ${esc(top.impact)}</div><div class="action-row"><a class="btn primary" href="#${esc(top.route)}">Open intelligence</a>${sourceButton(top.source,'Evidence')}${watchButton('story',top.id,top.title)}</div></article>
 <div class="signal-stack"><div class="signal-card"><div class="signal-label">Portugal · H1 2026</div><div class="signal-value">66.3 t</div><div class="signal-desc">Exports of plant, preparations & substances</div><div class="signal-change">Export-hub signal</div></div><div class="signal-card"><div class="signal-label">Denmark · 2025</div><div class="signal-value">+64%</div><div class="signal-desc">Redeemed prescriptions YoY</div><div class="signal-change">Demand accelerating</div></div><div class="signal-card"><div class="signal-label">Radar evidence</div><div class="signal-value">${D.meta.observations.toLocaleString()}</div><div class="signal-desc">Current observations</div><div class="signal-change">${D.meta.variablesReady}/${D.meta.variablesTotal} core variables covered</div></div></div></div>
 <section class="section">${sectionHead('Three things worth your attention','What changed, why it matters and where to go next.') }<div class="grid grid-3">${rest.map(storyCard).join('')}</div></section>
 <section class="section">${sectionHead('Markets moving now','A fast cross-market read.','#markets')}<div class="grid grid-3">${D.markets.slice(0,3).map(countryCard).join('')}</div></section>
 <section class="section">${sectionHead('Open commercial opportunities','Only items with a defensible sector fit.','#opportunities')}<div class="grid grid-3">${D.opportunities.map(opportunityCard).join('')}</div></section>
 <section class="section">${sectionHead('Watchlist','Save countries, companies, laws and opportunities to make Today personal.','#watchlist',state.watch.size?'Open watchlist':'Build watchlist')} ${watchPreview()}</section>`
}
function countryCard(m){return `<article class="country-card searchable" data-route="market/${m.id}"><div class="country-title"><div><div class="country-kicker">${esc(m.region)} · ${esc(m.status)}</div><h3>${esc(m.name)}</h3></div><span class="status-pill tone-${m.signalTone}">${esc(m.signal)}</span></div><div class="country-headline">${esc(m.headline)}</div>${m.metrics.slice(0,3).map(x=>`<div class="stat-row"><span>${esc(x.label)}</span><b>${esc(x.value)}</b></div>`).join('')}</article>`}
function opportunityCard(o){return `<article class="opportunity-card searchable" data-route="opportunity/${o.id}"><div class="meta-row">${badge(o.fit)}<span>${esc(o.country)} · ${esc(o.kind)}</span></div><h3>${esc(o.title)}</h3><p>${esc(o.summary)}</p><div class="buyer">Buyer: ${esc(o.buyer)}</div><div class="deadline">Open · ${esc(o.deadline)}</div></article>`}
function watchPreview(){if(!state.watch.size)return `<div class="empty">Nothing saved yet. Use ☆ Watch anywhere in the Radar to build a personal monitoring list.</div>`;const items=resolveWatchItems().slice(0,6);return `<div class="grid grid-3">${items.map(w=>`<article class="entity-card" data-route="${w.route}"><div class="meta-row">${badge(w.type)}</div><h3>${esc(w.label)}</h3><p>${esc(w.summary||'Saved to your intelligence watchlist.')}</p><div class="entity-foot"><span>Watching</span><span>Open →</span></div></article>`).join('')}</div>`}
function marketsView(){return `${head('Markets','Markets','Compare demand, supply, trade, product, pricing and regulatory capacity without jumping between sources.')}
 <div class="filterbar"><div class="tabs" id="marketTabs">${['all','positive','watch','new','neutral'].map(f=>`<button class="tab ${state.marketFilter===f?'active':''}" data-market-filter="${f}">${f==='all'?'All markets':f[0].toUpperCase()+f.slice(1)}</button>`).join('')}</div><span class="count-label">${D.markets.length} profiled markets in preview</span></div>
 <div class="grid grid-3">${D.markets.filter(m=>state.marketFilter==='all'||m.signalTone===state.marketFilter).map(countryCard).join('')}</div>
 <section class="section">${sectionHead('Fast comparison','Key signals across the current preview.','#compare','Open comparison')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Market</th><th>Position</th><th>Signal</th><th>Key metric</th><th>Evidence</th></tr></thead><tbody>${D.markets.map(m=>`<tr data-route="market/${m.id}"><td><strong>${esc(m.name)}</strong></td><td>${esc(m.status)}</td><td><span class="status-pill tone-${m.signalTone}">${esc(m.signal)}</span></td><td>${esc(m.metrics[0].value)} · ${esc(m.metrics[0].label)}</td><td>${esc(source(m.metrics[0].source)?.name||'')}</td></tr>`).join('')}</tbody></table></div></section>`}
function marketProfile(id){const m=D.markets.find(x=>x.id===id);if(!m)return notFound();const related=D.today.filter(i=>i.entities?.includes(id));return `${head('Market profile',m.name,m.description)}<section class="profile-hero"><div class="profile-top"><div class="profile-title"><div class="eyebrow">${esc(m.region)} · ${esc(m.status)}</div><h1>${esc(m.name)}</h1><p class="page-copy">${esc(m.headline)}</p><div class="tag-row">${m.categories.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div class="profile-actions">${watchButton('market',m.id,m.name)}<a class="btn" href="#compare">Compare</a></div></div></section>
 <section class="section">${sectionHead('Key indicators','Every metric keeps its evidence attached.')}<div class="grid grid-4">${m.metrics.map(metricCard).join('')}</div></section>
 <section class="section"><div class="grid grid-2"><div class="panel">${sectionHead('Questions this market can answer')}<div class="question-list">${m.questions.map(q=>`<div class="question">${esc(q)}</div>`).join('')}</div></div><div class="panel">${sectionHead('Evidence stack')}<div class="grid grid-2">${m.sources.map(sourceMini).join('')}</div></div></div></section>
 <section class="section">${sectionHead('Related intelligence','News, company moves and regulation automatically converge on the market profile.')}<div class="grid grid-3">${related.length?related.map(storyCard).join(''):`<div class="empty">No recent material item in this preview snapshot.</div>`}</div></section>
 <section class="section">${sectionHead('Related markets')}<div class="grid grid-3">${m.related.map(r=>D.markets.find(x=>x.id===r)).filter(Boolean).map(countryCard).join('')}</div></section>`}
function metricCard(x){return `<div class="metric-card"><div class="metric-label">${esc(x.label)}</div><div class="metric-value">${esc(x.value)}</div><div class="metric-detail">${esc(x.detail)}</div><button class="metric-source" data-source="${esc(x.source)}">${esc(source(x.source)?.name||'Evidence')} →</button></div>`}
function sourceMini(id){const s=source(id);return s?`<div class="source-card"><div class="source-grade">${esc(s.grade)} · ${esc(s.type)}</div><h3>${esc(s.name)}</h3><p>${esc(s.note)}</p><button class="metric-source" data-source="${esc(id)}">Inspect source →</button></div>`:''}
function companiesView(){return `${head('Companies','Companies','Follow where strategic value is concentrating: cultivation, EU-GMP, pharmacy access, distribution, M&A and market entry.')}<div class="grid grid-3">${D.companies.map(c=>companyCard(c)).join('')}</div>`}
function companyCard(c){return `<article class="entity-card searchable" data-route="company/${c.id}"><div class="meta-row">${badge(c.type,'company')}<span>${esc(c.countries.join(' · '))}</span></div><h3>${esc(c.name)}</h3><p>${esc(c.headline)}</p><div class="tag-row" style="margin-top:10px">${c.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div><div class="entity-foot"><span>${esc(source(c.source)?.name||'')}</span><span>Open profile →</span></div></article>`}
function companyProfile(id){const c=D.companies.find(x=>x.id===id);if(!c)return notFound();const news=D.today.filter(i=>i.entities?.some(e=>e.toLowerCase()===c.name.toLowerCase()||e===c.id));return `${head('Company profile',c.name,c.summary)}<section class="profile-hero"><div class="profile-top"><div class="profile-title"><div class="eyebrow">${esc(c.type)} · ${esc(c.countries.join(' / '))}</div><h1>${esc(c.name)}</h1><p class="page-copy">${esc(c.headline)}</p><div class="tag-row">${c.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div class="profile-actions">${watchButton('company',c.id,c.name)}${sourceButton(c.source,'Primary disclosure')}</div></div></section><section class="section">${sectionHead('Key company signals')}<div class="grid grid-3">${c.metrics.map(x=>`<div class="metric-card"><div class="metric-label">${esc(x.label)}</div><div class="metric-value">${esc(x.value)}</div><div class="metric-detail">${esc(x.detail)}</div></div>`).join('')}</div></section><section class="section">${sectionHead('Related intelligence')}<div class="grid grid-3">${news.length?news.map(storyCard).join(''):`<div class="empty">No additional material item in this preview snapshot.</div>`}</div></section>`}
function productsView(){const markets=['all',...new Set(D.products.map(p=>p.market))],forms=['all',...new Set(D.products.map(p=>p.form))];const list=D.products.filter(p=>(state.productMarket==='all'||p.market===state.productMarket)&&(state.productForm==='all'||p.form===state.productForm));return `${head('Products','Products & pricing','Connect cannabinoid profile, dosage form, availability, price positioning and market access to actual demand.')}<div class="filterbar"><select class="filter-select" id="productMarket">${markets.map(x=>`<option value="${esc(x)}" ${x===state.productMarket?'selected':''}>${x==='all'?'All markets':x}</option>`).join('')}</select><select class="filter-select" id="productForm">${forms.map(x=>`<option value="${esc(x)}" ${x===state.productForm?'selected':''}>${x==='all'?'All forms':x}</option>`).join('')}</select><span class="count-label">${list.length} product intelligence records</span></div><div class="grid grid-3">${list.map(productCard).join('')}</div><section class="section">${sectionHead('What product intelligence should answer','The product layer is designed around commercial decisions, not strain catalogues.')}<div class="grid grid-3"><div class="panel"><h2>Demand fit</h2><p class="page-copy">Which THC/CBD bands, forms and price points actually move in each market?</p></div><div class="panel"><h2>White space</h2><p class="page-copy">Where is availability low relative to patient demand or reimbursement?</p></div><div class="panel"><h2>Competitive pressure</h2><p class="page-copy">Which suppliers, origins and brands are compressing price or gaining share?</p></div></div></section>`}
function productCard(p){return `<article class="product-card searchable"><div class="meta-row">${badge(p.form)}<span>${esc(p.market)} · ${esc(p.demand)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.cannabinoids)}</p><div class="why-line"><b>Read-through:</b> ${esc(p.note)}</div><div class="story-foot"><span>${esc(p.price)}</span><button class="metric-source" data-source="${esc(p.source)}">${esc(p.evidence)} →</button></div></article>`}
function regulationView(){const countries=['all',...new Set(D.regulations.map(r=>r.country))];const list=D.regulations.filter(r=>state.regCountry==='all'||r.country===state.regCountry);return `${head('Regulation','Regulation & policy','Track law as a live process: current status, effective date, affected actors, commercial impact and what changes next.')}<div class="filterbar"><select class="filter-select" id="regCountry">${countries.map(x=>`<option value="${x}" ${x===state.regCountry?'selected':''}>${x==='all'?'All geographies':x}</option>`).join('')}</select><span class="count-label">${list.length} active regulatory threads</span></div><div class="grid grid-2">${list.map(regCard).join('')}</div>`}
function regCard(r){return `<article class="reg-card searchable" data-route="regulation/${r.id}"><div class="meta-row">${badge(r.status,'regulation')}<span>${esc(r.country)} · ${esc(r.updated)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary)}</p><div class="why-line"><b>Affected:</b> ${esc(r.affected.join(' · '))}</div><div class="story-foot"><span>Impact: ${esc(r.impact)}</span><span>${esc(source(r.source)?.name||'')}</span></div></article>`}
function regulationProfile(id){const r=D.regulations.find(x=>x.id===id);if(!r)return notFound();return `${head('Regulatory tracker',r.title,r.summary)}<section class="profile-hero"><div class="profile-top"><div class="profile-title"><div class="eyebrow">${esc(r.country)} · ${esc(r.status)}</div><h1>${esc(r.title)}</h1><p class="page-copy">Effective: ${esc(r.effective)} · Last update: ${esc(r.updated)}</p></div><div class="profile-actions">${watchButton('regulation',r.id,r.title)}${sourceButton(r.source,'Official source')}</div></div></section><section class="section"><div class="grid grid-3"><div class="metric-card"><div class="metric-label">Status</div><div class="metric-value" style="font-size:19px">${esc(r.status)}</div><div class="metric-detail">Current tracked state</div></div><div class="metric-card"><div class="metric-label">Commercial impact</div><div class="metric-value">${esc(r.impact)}</div><div class="metric-detail">Radar editorial assessment</div></div><div class="metric-card"><div class="metric-label">Effective</div><div class="metric-value" style="font-size:19px">${esc(r.effective)}</div><div class="metric-detail">Current effective / expected timing</div></div></div></section><section class="section"><div class="grid grid-2"><div class="panel">${sectionHead('Who is affected')}<div class="question-list">${r.affected.map(x=>`<div class="question">${esc(x)}</div>`).join('')}</div></div><div class="panel">${sectionHead('What to watch next')}<p class="page-copy">${esc(r.watch)}</p><div class="action-row">${sourceButton(r.source,'Inspect evidence')}</div></div></div></section>`}
function opportunitiesView(){const countries=['all',...new Set(D.opportunities.map(o=>o.country))];const list=D.opportunities.filter(o=>state.oppCountry==='all'||o.country===state.oppCountry);return `${head('Opportunities','Commercial opportunities','Turn fragmented tenders, contracts, funding and market-entry signals into an actionable pipeline.')}<div class="filterbar"><select class="filter-select" id="oppCountry">${countries.map(x=>`<option value="${esc(x)}" ${x===state.oppCountry?'selected':''}>${x==='all'?'All geographies':x}</option>`).join('')}</select><span class="count-label">${list.length} verified sector-linked opportunities</span></div><div class="grid grid-3">${list.map(opportunityCard).join('')}</div><section class="section">${sectionHead('Pipeline logic','Every item should tell the user whether it is worth acting on.')}<div class="table-wrap"><table class="data-table"><thead><tr><th>Opportunity</th><th>Buyer</th><th>Fit</th><th>Deadline</th><th>Status</th></tr></thead><tbody>${list.map(o=>`<tr data-route="opportunity/${o.id}"><td><strong>${esc(o.title)}</strong></td><td>${esc(o.buyer)}</td><td>${esc(o.fit)}</td><td>${esc(o.deadline)}</td><td><span class="status-pill tone-positive">${esc(o.status)}</span></td></tr>`).join('')}</tbody></table></div></section>`}
function opportunityProfile(id){const o=D.opportunities.find(x=>x.id===id);if(!o)return notFound();return `${head('Opportunity',o.title,o.summary)}<section class="profile-hero"><div class="profile-top"><div class="profile-title"><div class="eyebrow">${esc(o.country)} · ${esc(o.kind)} · ${esc(o.fit)}</div><h1>${esc(o.title)}</h1><p class="page-copy">Buyer: ${esc(o.buyer)}</p></div><div class="profile-actions">${watchButton('opportunity',o.id,o.title)}<a class="btn primary" href="${esc(o.url)}" target="_blank" rel="noopener">Open official notice</a></div></div></section><section class="section"><div class="grid grid-3"><div class="metric-card"><div class="metric-label">Status</div><div class="metric-value">${esc(o.status)}</div><div class="metric-detail">Current lifecycle</div></div><div class="metric-card"><div class="metric-label">Deadline</div><div class="metric-value" style="font-size:18px">${esc(o.deadline)}</div><div class="metric-detail">Official notice deadline</div></div><div class="metric-card"><div class="metric-label">Sector fit</div><div class="metric-value" style="font-size:18px">${esc(o.fit)}</div><div class="metric-detail">Verified relevance</div></div></div></section><section class="section"><div class="grid grid-2"><div class="panel">${sectionHead('Who should care')}<p class="page-copy">${esc(o.who)}</p></div><div class="panel">${sectionHead('Evidence')}<p class="page-copy">Primary procurement notice verified through TED / official buyer channel.</p><div class="action-row">${sourceButton(o.source,'Inspect source policy')}</div></div></div></section>`}
function compareView(){const selected=D.markets.filter(m=>state.compare.has(m.id));return `${head('Compare','Compare markets','Put countries side by side across demand, supply, trade, products and regulatory structure.')}<div class="compare-grid">${D.markets.map(m=>`<label class="compare-card"><div class="compare-check"><input type="checkbox" data-compare="${m.id}" ${state.compare.has(m.id)?'checked':''}><strong>${esc(m.name)}</strong></div><div class="country-headline">${esc(m.headline)}</div></label>`).join('')}</div><section class="section">${sectionHead('Selected comparison',`${selected.length} markets selected`)}${selected.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Dimension</th>${selected.map(m=>`<th>${esc(m.name)}</th>`).join('')}</tr></thead><tbody><tr><td><strong>Position</strong></td>${selected.map(m=>`<td>${esc(m.status)}</td>`).join('')}</tr><tr><td><strong>Signal</strong></td>${selected.map(m=>`<td><span class="status-pill tone-${m.signalTone}">${esc(m.signal)}</span></td>`).join('')}</tr>${[0,1,2,3].map(i=>`<tr><td><strong>${esc(selected[0]?.metrics[i]?.label||`Metric ${i+1}`)}</strong></td>${selected.map(m=>`<td>${esc(m.metrics[i]?.value||'—')}<br><span style="color:#71877b">${esc(m.metrics[i]?.label||'')}</span></td>`).join('')}</tr>`).join('')}</tbody></table></div>`:`<div class="empty">Select at least one market.</div>`}</section>`}
function watchlistView(){const items=resolveWatchItems();const groups={market:[],company:[],regulation:[],opportunity:[],story:[]};items.forEach(i=>(groups[i.type]||groups.story).push(i));return `${head('Personal workspace','Watchlist','A single place for the markets, companies, regulations and opportunities you actually care about.')} ${items.length?Object.entries(groups).filter(([,v])=>v.length).map(([k,v])=>`<section class="watchlist-group">${sectionHead(k[0].toUpperCase()+k.slice(1),`${v.length} watched`)}<div class="grid grid-3">${v.map(w=>`<article class="entity-card" data-route="${w.route}"><div class="meta-row">${badge(w.type)}</div><h3>${esc(w.label)}</h3><p>${esc(w.summary||'Saved intelligence entity.')}</p><div class="action-row">${watchButton(w.type,w.id,w.label)}</div></article>`).join('')}</div></section>`).join(''):`<div class="empty">Your watchlist is empty. Add ☆ Watch from any market, company, regulation or opportunity.</div>`}`}
function methodologyView(){return `${head('Evidence','Evidence & methodology','The Radar is designed to replace source-hopping without hiding where information came from.')}<div class="grid grid-3"><div class="panel"><div class="eyebrow">Tier A</div><h2>Primary evidence</h2><p class="page-copy">Regulators, government datasets, statutory registers, parliament, procurement portals and formal filings support factual publication.</p></div><div class="panel"><div class="eyebrow">Tier B</div><h2>Strong secondary evidence</h2><p class="page-copy">Peer-reviewed research and robust methodological datasets can support defined analytical claims.</p></div><div class="panel"><div class="eyebrow">Tier C / D</div><h2>Discovery & context</h2><p class="page-copy">Specialist intelligence, market trackers and community sources are discovery layers, not substitutes for primary evidence when primary evidence exists.</p></div></div><section class="section">${sectionHead('Source library','Inspect the evidence classes used in this preview.')}<div class="grid grid-3">${Object.keys(D.sources).map(sourceMini).join('')}</div></section><section class="section"><div class="panel">${sectionHead('Product principle')}<p class="page-copy">The goal is not to make users visit 500 sources. The Radar should ingest, normalize, connect and explain them — then keep the original evidence one click away inside the same workflow.</p></div></section>`}
function sourceDrawer(id){const s=source(id);if(!s)return;const d=$('#drawer');d.innerHTML=`<div class="drawer-head"><div>${badge(s.grade==='A'?'Primary evidence':s.grade==='B'?'Research evidence':s.grade==='Company'?'Company disclosure':'Secondary intelligence',s.grade==='A'?'official':s.grade==='Company'?'company':'')}</div><button class="drawer-close" data-close-drawer>×</button></div><h2>${esc(s.name)}</h2><div class="meta-row"><span>${esc(s.type)}</span><span>Evidence grade ${esc(s.grade)}</span></div><p>${esc(s.note)}</p><div class="evidence-box"><strong>Radar source policy</strong><br>${s.grade==='A'?'This source can support factual publication when the relevant definition, period and geography match.':s.grade==='B'?'This source can support defined research/analytical claims, with methodology preserved.':s.grade==='Company'?'This is a company disclosure and is shown as a company claim, not regulator statistics.':'This source is used for discovery, triangulation or context. Primary evidence is preferred for factual metrics.'}</div><div class="action-row"><a class="btn primary" href="${esc(s.url)}" target="_blank" rel="noopener">Open original source</a><button class="btn" data-close-drawer>Close</button></div>`;d.classList.add('open');d.setAttribute('aria-hidden','false')}
function closeDrawer(){const d=$('#drawer');d.classList.remove('open');d.setAttribute('aria-hidden','true')}
function resolveWatchItems(){const out=[];for(const k of state.watch){const [type,...ids]=k.split(':');const id=ids.join(':');let obj,route,label,summary;if(type==='market'){obj=D.markets.find(x=>x.id===id);route=`market/${id}`;label=obj?.name;summary=obj?.headline}else if(type==='company'){obj=D.companies.find(x=>x.id===id);route=`company/${id}`;label=obj?.name;summary=obj?.headline}else if(type==='regulation'){obj=D.regulations.find(x=>x.id===id);route=`regulation/${id}`;label=obj?.title;summary=obj?.summary}else if(type==='opportunity'){obj=D.opportunities.find(x=>x.id===id);route=`opportunity/${id}`;label=obj?.title;summary=obj?.summary}else if(type==='story'){obj=D.today.find(x=>x.id===id);route=obj?.route;label=obj?.title;summary=obj?.summary}if(obj)out.push({type,id,route,label,summary})}return out}
function notFound(){return `${head('Radar','Not found','This entity is not present in the current preview dataset.')}<div class="empty"><a href="#today">Return to Today</a></div>`}
function buildSearchIndex(){const a=[];D.markets.forEach(x=>a.push({type:'Market',title:x.name,sub:x.headline,route:`market/${x.id}`,tokens:[x.id,...x.categories]}));D.companies.forEach(x=>a.push({type:'Company',title:x.name,sub:x.headline,route:`company/${x.id}`,tokens:[...x.tags,...x.countries]}));D.products.forEach(x=>a.push({type:'Product',title:x.name,sub:`${x.market} · ${x.cannabinoids}`,route:'products',tokens:[x.form,x.market,x.cannabinoids]}));D.regulations.forEach(x=>a.push({type:'Regulation',title:x.title,sub:`${x.country} · ${x.status}`,route:`regulation/${x.id}`,tokens:[x.country,...x.affected]}));D.opportunities.forEach(x=>a.push({type:'Opportunity',title:x.title,sub:`${x.country} · ${x.deadline}`,route:`opportunity/${x.id}`,tokens:[x.country,x.fit,x.buyer]}));D.today.forEach(x=>a.push({type:'Intelligence',title:x.title,sub:`${x.country} · ${x.category}`,route:x.route,tokens:x.entities||[]}));return a}
const searchIndex=buildSearchIndex();
function openSearch(seed=''){const p=$('#commandPalette');p.hidden=false;p.innerHTML=`<div class="command-box"><div class="command-input-wrap"><span>⌕</span><input id="commandInput" class="command-input" placeholder="Ask or search the Radar…" value="${esc(seed)}"><span class="command-hint">ESC</span></div><div class="command-results" id="commandResults"></div></div>`;const input=$('#commandInput');input.focus();function go(){const q=input.value.trim().toLowerCase();const terms=q.split(/\s+/).filter(Boolean);const scored=searchIndex.map(x=>{const hay=[x.title,x.sub,...(x.tokens||[])].join(' ').toLowerCase();const score=terms.reduce((n,t)=>n+(hay.includes(t)?1:0),0);return {...x,score}}).filter(x=>!terms.length||x.score>0).sort((a,b)=>b.score-a.score).slice(0,18);$('#commandResults').innerHTML=scored.length?scored.map(x=>`<div class="search-result" data-search-route="${esc(x.route)}"><div class="result-icon">${esc(x.type[0])}</div><div><div class="result-title">${esc(x.title)}</div><div class="result-sub">${esc(x.sub)}</div></div><div class="result-type">${esc(x.type)}</div></div>`).join(''):`<div class="empty">No direct match. Try a country, company, product, law or opportunity.</div>`}input.addEventListener('input',go);go()}
function closeSearch(){const p=$('#commandPalette');p.hidden=true;p.innerHTML=''}
function parseRoute(){const raw=location.hash.replace(/^#/,'')||'today';const parts=raw.split('/');if(parts[0]==='search'){openSearch();history.replaceState(null,'','#today');return {route:'today',params:[]}}return {route:parts[0],params:parts.slice(1)}}
function render(){const r=parseRoute();state.route=r.route;state.params=r.params;renderShell();let html='';switch(r.route){case'today':html=todayView();break;case'markets':html=marketsView();break;case'market':html=marketProfile(r.params[0]);break;case'companies':html=companiesView();break;case'company':html=companyProfile(r.params[0]);break;case'products':html=productsView();break;case'regulation':html=r.params[0]?regulationProfile(r.params[0]):regulationView();break;case'opportunities':html=opportunitiesView();break;case'opportunity':html=opportunityProfile(r.params[0]);break;case'compare':html=compareView();break;case'watchlist':html=watchlistView();break;case'methodology':html=methodologyView();break;default:html=notFound()}$('#main').innerHTML=html;window.scrollTo({top:0,behavior:'instant'});bindDynamic()}
function bindDynamic(){
  $$('[data-route]').forEach(el=>el.addEventListener('click',e=>{if(e.target.closest('button,a,input,select'))return;location.hash=el.dataset.route}));
  $$('[data-source]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();sourceDrawer(el.dataset.source)}));
  $$('[data-watch-type]').forEach(el=>el.addEventListener('click',e=>{e.stopPropagation();toggleWatch(el.dataset.watchType,el.dataset.watchId,el.dataset.watchLabel)}));
  $$('[data-market-filter]').forEach(el=>el.addEventListener('click',()=>{state.marketFilter=el.dataset.marketFilter;render()}));
  $('#productMarket')?.addEventListener('change',e=>{state.productMarket=e.target.value;render()}); $('#productForm')?.addEventListener('change',e=>{state.productForm=e.target.value;render()});
  $('#regCountry')?.addEventListener('change',e=>{state.regCountry=e.target.value;render()}); $('#oppCountry')?.addEventListener('change',e=>{state.oppCountry=e.target.value;render()});
  $$('[data-compare]').forEach(el=>el.addEventListener('change',e=>{e.target.checked?state.compare.add(e.target.dataset.compare):state.compare.delete(e.target.dataset.compare);render()}));
}
function openNav(){const s=$('#sidebar'),b=$('#backdrop');s.classList.add('open');b.hidden=false;document.body.classList.add('nav-open')}
function closeNav(){const s=$('#sidebar'),b=$('#backdrop');s.classList.remove('open');b.hidden=true;document.body.classList.remove('nav-open')}
document.addEventListener('click',e=>{
  if(e.target.closest('[data-open-search]')){e.preventDefault();closeNav();openSearch();return}
  if(e.target.closest('[data-close-nav]')){closeNav();return}
  if(e.target.closest('#menuBtn')){openNav();return}
  if(e.target.id==='backdrop'){closeNav();return}
  if(e.target.closest('.sidebar a')&&innerWidth<=860)closeNav();
  const sr=e.target.closest('[data-search-route]');if(sr){closeSearch();location.hash=sr.dataset.searchRoute;return}
  if(e.target.closest('[data-close-drawer]'))closeDrawer();
});
document.addEventListener('keydown',e=>{if(e.key==='/'&&!/input|textarea|select/i.test(document.activeElement.tagName)){e.preventDefault();openSearch()}if(e.key==='Escape'){if(!$('#commandPalette').hidden)closeSearch();else if($('#drawer').classList.contains('open'))closeDrawer();else closeNav()}});
$('#commandPalette').addEventListener('click',e=>{if(e.target.id==='commandPalette')closeSearch()});
window.addEventListener('hashchange',render); window.addEventListener('resize',()=>{if(innerWidth>860)closeNav()});
render();
})();
