window.RADAR_DATA = {
  meta: {
    product: "Cannabis Intelligence Radar",
    scope: "Europe & international medical cannabis",
    updated: "2026-09-13T18:11:46Z",
    updatedLabel: "13 Sep 2026 · 19:11 Lisbon",
    observations: 7910,
    variablesReady: 24,
    variablesTotal: 28,
    sourceCandidates: 17962,
    tier1Markets: 15
  },
  sources: {
    infarmed: {name:"INFARMED", type:"Official regulator", grade:"A", url:"https://www.infarmed.pt/web/infarmed/canabis-medicinal", note:"Portugal medicinal-cannabis regulatory and sector information."},
    bfarm: {name:"BfArM", type:"Official regulator", grade:"A", url:"https://www.bfarm.de/DE/Bundesopiumstelle/Medizinisches-Cannabis/_node.html", note:"Germany medical-cannabis import and regulatory information."},
    dkma: {name:"Danish Medicines Agency", type:"Official regulator", grade:"A", url:"https://laegemiddelstyrelsen.dk/en/special/medicinal-cannabis/", note:"Denmark medicinal-cannabis programme, products and safety data."},
    sukl: {name:"SÚKL", type:"Official regulator", grade:"A", url:"https://sukl.gov.cz/statistika-konopi-pro-lecebne-pouziti/statistika-vydeju-konopi-pro-lecebne-pouziti-v-lekarnach/", note:"Czech medical-cannabis dispensing and patient statistics."},
    aemps: {name:"AEMPS", type:"Official regulator", grade:"A", url:"https://www.aemps.gob.es/medicamentos-de-uso-humano/estupefacientes-y-psicotropos/", note:"Spanish narcotics, cultivation authorisations and standardized cannabis preparations."},
    edqm: {name:"EDQM / European Pharmacopoeia", type:"Official supranational", grade:"A", url:"https://www.edqm.eu/", note:"European Pharmacopoeia standards and monographs."},
    bundestag: {name:"Deutscher Bundestag", type:"Official parliament", grade:"A", url:"https://www.bundestag.de/", note:"German parliamentary legislation, hearings and official notices."},
    govil: {name:"Israel Ministry of Health", type:"Official ministry", grade:"A", url:"https://www.gov.il/en/departments/ministry_of_health", note:"Monthly medical-cannabis licence and programme publications."},
    ted: {name:"TED — Tenders Electronic Daily", type:"Official procurement", grade:"A", url:"https://ted.europa.eu/", note:"EU public procurement notices."},
    sec: {name:"SEC filings", type:"Statutory filing", grade:"A", url:"https://www.sec.gov/edgar/search/", note:"Public-company filings and material disclosures."},
    rwb: {name:"Red White & Bloom", type:"Company disclosure", grade:"Company", url:"https://ir.redwhitebloom.com/news-events/press-releases/detail/178/red-white-bloom-brands-expands-into-europe-with-strategic", note:"Issuer disclosure; not regulator statistics."},
    aurora: {name:"Aurora Cannabis", type:"Company filing", grade:"Company", url:"https://www.sec.gov/Archives/edgar/data/1683541/000127956926000846/ex991.htm", note:"Company statement filed publicly."},
    tilray: {name:"Tilray", type:"Company disclosure", grade:"Company", url:"https://www.globenewswire.com/news-release/2026/08/20/3348209/0/en/tilray-strengthens-global-medical-cannabis-leadership-with-major-production-increase-to-meet-international-demand.html", note:"Company release; strategic signal only."},
    pubmed: {name:"PubMed / peer-reviewed study", type:"Academic evidence", grade:"B", url:"https://pubmed.ncbi.nlm.nih.gov/", note:"Peer-reviewed market or clinical evidence where applicable."},
    cannamonitor: {name:"Cannamonitor", type:"Specialist intelligence", grade:"C", url:"https://cannamonitor.com/", note:"Discovery and contextual analysis only when primary evidence exists."}
  },
  today: [
    {id:"pt-exports-h1", category:"Market", priority:1, country:"PT", date:"2026-08-21", age:"H1 2026 data", title:"Portugal exported 66.3 tonnes in H1 2026", summary:"INFARMED sector figures show 66,305 kg exported in the first half of 2026. Germany, Spain and Denmark are among the main destinations. The official category covers plant, preparations and substances — not automatically retail flower.", impact:"Portugal is increasingly an export and processing hub. Product form and final patient market must be analysed separately from customs destination.", entities:["PT","DE","ES","DK"], source:"infarmed", route:"market/PT"},
    {id:"dk-demand-2025", category:"Market", priority:1, country:"DK", date:"2026-09-11", age:"2 days ago", title:"Denmark reports +64% redeemed prescriptions in 2025", summary:"The Danish Medicines Agency reported 64% year-on-year growth in redeemed prescriptions and 54% growth in citizens redeeming prescriptions in 2025.", impact:"A small but transparent market is showing measurable demand acceleration as the programme enters its permanent phase.", entities:["DK"], source:"dkma", route:"market/DK"},
    {id:"rwb-heal", category:"Companies", priority:1, country:"DE / UK", date:"2026-09-11", age:"2 days ago", title:"RWB takes control of HEAL Europe / Grünhorn platform", summary:"RWB says the platform handled more than 12 tonnes and approximately 290,000 prescriptions in the 12 months ended July 2026.", impact:"European consolidation is increasingly about patient access, pharmacy/distribution and logistics — not cultivation alone.", entities:["RWB","HEAL","Grünhorn","DE","UK"], source:"rwb", route:"company/RWB"},
    {id:"es-register", category:"Regulation", priority:1, country:"ES", date:"2026-08-11", age:"Updated Aug 2026", title:"Spain’s standardized-cannabis preparation register is operational", summary:"AEMPS maintains the route created under Royal Decree 903/2025 for standardized cannabis preparations used in hospital magistral formulas.", impact:"Spain now has a formal pharmaceutical pathway, but it is not a German-style broad retail-flower market.", entities:["ES","AEMPS"], source:"aemps", route:"regulation/es-standardized"},
    {id:"de-reimbursement", category:"Regulation", priority:2, country:"DE", date:"2026-08-28", age:"16 days ago", title:"Germany changes reimbursement sequencing for cannabis medicines", summary:"A Bundestag notice describes a reimbursement priority affecting standardized extracts and dronabinol/nabilone products.", impact:"Payer rules can shift demand across finished medicines, extracts and compounded formulations even without changing basic legality.", entities:["DE"], source:"bundestag", route:"regulation/de-reimbursement"},
    {id:"aurora-curaleaf", category:"Companies", priority:2, country:"Global / EU", date:"2026-09-02", age:"11 days ago", title:"Aurora urges shareholders to reject Curaleaf’s hostile bid", summary:"Aurora argues the offer undervalues its international medical platform and future upside.", impact:"EU-GMP capacity, distribution access and international medical revenue are being valued as strategic acquisition assets.", entities:["Aurora","Curaleaf"], source:"aurora", route:"company/Aurora"}
  ],
  markets: [
    {id:"PT", name:"Portugal", region:"Europe", status:"Export hub", signal:"Accelerating trade", signalTone:"positive", headline:"Export-led European supply hub", description:"Strong visibility on production, trade, licensed capacity and GMP infrastructure, with domestic patient demand much smaller than external supply-chain activity.", metrics:[
      {label:"H1 2026 exports", value:"66.3 t", detail:"Plant, preparations & substances", source:"infarmed"},
      {label:"2025 exports", value:"79.9 t", detail:"Full-year sector figure", source:"infarmed"},
      {label:"H1 2026 prescriptions", value:"5,413", detail:"Domestic prescriptions", source:"infarmed"},
      {label:"Key destinations", value:"DE · ES · DK", detail:"Main published destinations", source:"infarmed"}
    ], questions:["How much of Portuguese volume is domestically produced vs imported for processing?","Which destination markets are absorbing incremental supply?","Which licensed operators have EU-GMP and export capability?"], categories:["Supply","Trade","GMP","Operators","Prescriptions"], sources:["infarmed","edqm"], related:["DE","ES","DK"]},
    {id:"DE", name:"Germany", region:"Europe", status:"Largest EU demand hub", signal:"High demand / price pressure", signalTone:"watch", headline:"Europe’s scale market — with rising competitive pressure", description:"The largest European commercial opportunity combines import dependence, high product variety and intense competition across price, access and distribution.", metrics:[
      {label:"2025 imports", value:"~201 t", detail:"BfArM-reported annual scale", source:"bfarm"},
      {label:"Dominant flower demand band", value:"20–29.9% THC", detail:"> two-thirds in peer-reviewed dispensary dataset", source:"pubmed"},
      {label:"Observed product universe", value:"996", detail:"Distinct flower products in 2024–25 study", source:"pubmed"},
      {label:"Strategic issue", value:"Access", detail:"Telemedicine, pharmacy, reimbursement", source:"bundestag"}
    ], questions:["Which suppliers are gaining origin share?","Where is price compression strongest?","How are reimbursement and telemedicine rules changing channel economics?"], categories:["Demand","Imports","Pricing","Products","Reimbursement"], sources:["bfarm","bundestag","pubmed"], related:["PT","CA","DK"]},
    {id:"DK", name:"Denmark", region:"Europe", status:"Transparent benchmark", signal:"Demand accelerating", signalTone:"positive", headline:"Small market, exceptional data transparency", description:"Patient, prescription, product, price and dispensed-volume evidence can be connected, making Denmark valuable for price × product × access analysis.", metrics:[
      {label:"2025 redeemed prescriptions", value:"+64%", detail:"Year-on-year growth", source:"dkma"},
      {label:"Citizens redeeming", value:"+54%", detail:"Year-on-year growth", source:"dkma"},
      {label:"Retail price observations", value:"188", detail:"Radar collected observations", source:"dkma"},
      {label:"Programme", value:"Permanent", detail:"From 1 Jan 2026", source:"dkma"}
    ], questions:["Which product profiles gain share as access grows?","How does price relate to prescription volume?","Which suppliers benefit from the permanent programme?"], categories:["Demand","Products","Pricing","Access"], sources:["dkma"], related:["DE","NL"]},
    {id:"CZ", name:"Czechia", region:"Europe", status:"Demand-series benchmark", signal:"Stable official series", signalTone:"neutral", headline:"Long official patient and dispensing history", description:"Monthly official series allow multi-year demand analysis instead of snapshot comparisons.", metrics:[
      {label:"Patient history", value:"42 months", detail:"Official monthly/quarterly series", source:"sukl"},
      {label:"Patient observations", value:"42", detail:"Latest compatible series", source:"sukl"},
      {label:"Dispensing history", value:"42 months", detail:"Official series", source:"sukl"},
      {label:"Latest period", value:"Jun 2026", detail:"Current Radar reference", source:"sukl"}
    ], questions:["Is patient growth accelerating or decelerating?","How closely do prescriptions track active patients?","Where are structural breaks in the series?"], categories:["Patients","Prescriptions","Dispensing"], sources:["sukl"], related:["DE","PL"]},
    {id:"IL", name:"Israel", region:"Middle East", status:"Access-system benchmark", signal:"Mature operating funnel", signalTone:"neutral", headline:"One of the richest access-system datasets", description:"Patients, sales, inventory, pharmacies, prescribers and cultivators can be connected into an end-to-end market funnel.", metrics:[
      {label:"Latest patient series", value:"13 obs", detail:"21-month compatible history", source:"govil"},
      {label:"Latest patient period", value:"May 2026", detail:"Official monthly status", source:"govil"},
      {label:"Access layers", value:"Patients → pharmacies", detail:"Multiple official datasets", source:"govil"},
      {label:"Supply layers", value:"Sales · inventory", detail:"Official programme publications", source:"govil"}
    ], questions:["How many pharmacies and prescribers serve each patient cohort?","Does inventory move ahead of or behind sales?","Where is access capacity constrained?"], categories:["Patients","Sales","Inventory","Pharmacies","Prescribers"], sources:["govil"], related:["DE","CA"]},
    {id:"ES", name:"Spain", region:"Europe", status:"Pharmaceutical pathway", signal:"New access route", signalTone:"new", headline:"Industrial and pharmaceutical market — not German-style retail flower", description:"Spain combines authorized cultivation and manufacturing with a newer standardized-preparation route for hospital magistral formulas.", metrics:[
      {label:"Standardized route", value:"Operational", detail:"AEMPS public register", source:"aemps"},
      {label:"Framework", value:"RD 903/2025", detail:"Effective Oct 2025", source:"aemps"},
      {label:"Cultivation", value:"Authorized", detail:"Medical/scientific purposes", source:"aemps"},
      {label:"Trade interpretation", value:"B2B ≠ retail", detail:"Imports can feed transformation/re-export", source:"aemps"}
    ], questions:["Which manufacturers can register standardized preparations?","Which Portuguese-Spanish flows are transformation vs patient supply?","Which authorized operators can become B2B counterparties?"], categories:["Regulation","Cultivation","Manufacturing","Trade"], sources:["aemps"], related:["PT","DE"]}
  ],
  companies: [
    {id:"RWB", name:"Red White & Bloom", type:"Public company", countries:["DE","UK","CA"], tags:["Distribution","Pharmacy","M&A"], headline:"Control of HEAL Europe / Grünhorn platform", summary:"RWB’s European strategy centers on pharmacy, distribution and patient-access infrastructure rather than cultivation alone.", metrics:[{label:"Prescriptions",value:"~290k",detail:"12 months to Jul 2026"},{label:"Volume",value:">12 t",detail:"Dispensed/distributed per company disclosure"}], source:"rwb"},
    {id:"Aurora", name:"Aurora Cannabis", type:"Public company", countries:["CA","DE","EU"], tags:["EU-GMP","Medical","M&A"], headline:"Defending independent value against Curaleaf bid", summary:"Aurora positions its international medical platform and European growth as core strategic value.", metrics:[{label:"Strategic signal",value:"M&A target",detail:"International medical platform"},{label:"Balance-sheet claim",value:"Debt-free",detail:"Per company statement"}], source:"aurora"},
    {id:"Tilray", name:"Tilray", type:"Public company", countries:["PT","DE","UK","EU"], tags:["Cultivation","EU-GMP","Distribution"], headline:"Portugal remains a strategic EU-GMP supply anchor", summary:"Tilray announced increased output at its Portugal facility to serve international medical demand.", metrics:[{label:"European anchor",value:"Portugal",detail:"EU-GMP production"},{label:"Target markets",value:"DE · UK · EU",detail:"International medical"}], source:"tilray"},
    {id:"Grünhorn", name:"Grünhorn", type:"Pharmacy / platform", countries:["DE"], tags:["Pharmacy","Patient access","Distribution"], headline:"Large German patient-access platform", summary:"A key example of how pharmacy and patient access can become strategic infrastructure in Europe.", metrics:[{label:"Prescriptions",value:"~290k",detail:"Platform group disclosure"},{label:"Market",value:"Germany",detail:"Medical cannabis"}], source:"rwb"}
  ],
  products: [
    {id:"de-flower-core", name:"High-THC medical flower", form:"Flower", market:"DE", cannabinoids:"20–29.9% THC · low CBD", price:"Price-sensitive", demand:"Core volume", evidence:"Peer-reviewed dispensary dataset", source:"pubmed", note:"More than two-thirds of demand in the observed German dataset sat in the 20–29.9% THC band; higher price correlated with lower demand."},
    {id:"dk-bedrocan", name:"Bedrocan", form:"Flower", market:"DK", cannabinoids:"~22% THC · <1% CBD", price:"Official programme", demand:"Admitted product", evidence:"Danish Medicines Agency", source:"dkma", note:"Example of high-THC flower admitted to the Danish medicinal-cannabis programme."},
    {id:"dk-bediol", name:"Bediol", form:"Flower", market:"DK", cannabinoids:"~6.3% THC · 8% CBD", price:"Official programme", demand:"Balanced profile", evidence:"Danish Medicines Agency", source:"dkma", note:"Shows that balanced THC/CBD profiles remain part of regulated European product mixes."},
    {id:"es-standardized", name:"Standardized cannabis preparations", form:"Preparation / extract", market:"ES", cannabinoids:"Defined THC/CBD", price:"Hospital pathway", demand:"New regulated route", evidence:"AEMPS", source:"aemps", note:"Registered standardized preparations can be used in typified magistral formulas under Spain’s framework."}
  ],
  regulations: [
    {id:"es-standardized", country:"ES", status:"Implemented", impact:"High", effective:"10 Oct 2025", updated:"11 Aug 2026", title:"Standardized cannabis preparations and hospital magistral formulas", summary:"Royal Decree 903/2025 created a formal route for standardized cannabis preparations, with AEMPS registration and hospital-pharmacy use.", affected:["Manufacturers","Hospital pharmacies","Specialist prescribers","Importers"], watch:"Registry growth, product approvals and supplier participation", source:"aemps"},
    {id:"de-reimbursement", country:"DE", status:"Implemented / monitor", impact:"High", effective:"2026", updated:"28 Aug 2026", title:"Reimbursement sequencing for cannabis-containing medicines", summary:"Reimbursement rules affect treatment sequencing across approved finished medicines, standardized extracts and dronabinol/nabilone.", affected:["Manufacturers","Pharmacies","Prescribers","Payers"], watch:"Prescribing mix and payer behaviour", source:"bundestag"},
    {id:"de-medcang", country:"DE", status:"Policy watch", impact:"High", effective:"Proposed", updated:"2026", title:"MedCanG amendment debate: telemedicine and pharmacy delivery", summary:"Policy debate continues around remote prescribing and delivery channels for medical-cannabis flower.", affected:["Telemedicine clinics","Pharmacies","Distributors","Flower suppliers"], watch:"Final enacted text and effective date", source:"bundestag"},
    {id:"dk-permanent", country:"DK", status:"Implemented", impact:"Medium", effective:"1 Jan 2026", updated:"2026", title:"Medicinal-cannabis programme made permanent", summary:"Denmark replaced the pilot scheme with a permanent framework while retaining product-admission controls.", affected:["Patients","Prescribers","Importers","Product suppliers"], watch:"Demand growth and product additions", source:"dkma"},
    {id:"eu-cannabis-flos", country:"EU", status:"Standards watch", impact:"Medium", effective:"TBD", updated:"Sep 2026", title:"European Pharmacopoeia Cannabis flos standards", summary:"Pharmacopoeial standards remain a critical quality layer for testing, specifications and release across European supply chains.", affected:["QA/QC","Manufacturers","Labs","Importers"], watch:"Final monograph revisions and implementation dates", source:"edqm"}
  ],
  opportunities: [
    {id:"tk-2026", title:"Open-House-Originale-Rabattverträge 2026-01 — Cannabis", country:"DE", kind:"Procurement", fit:"Direct cannabis", status:"Open", deadline:"31 Mar 2028", buyer:"Techniker Krankenkasse / participating sickness funds", summary:"Non-exclusive discount-contract route for eligible pharmaceutical companies supplying cannabis under the German reimbursement framework.", who:"Pharmaceutical suppliers with the required market-access and compliance capabilities.", source:"ted", url:"https://ted.europa.eu/en/notice/-/detail/113323-2026"},
    {id:"tk-2025", title:"Open-House-Originale-Rabattverträge 2025-09 — Cannabis", country:"DE", kind:"Procurement", fit:"Direct cannabis", status:"Open", deadline:"31 Mar 2027", buyer:"Techniker Krankenkasse", summary:"An additional open-house cannabis discount-contract route with standardized participation terms.", who:"Eligible pharma / cannabis suppliers capable of serving reimbursed German channels.", source:"ted", url:"https://ted.europa.eu/en/notice/-/detail/125418-2025"},
    {id:"eu4moldova", title:"EU4Moldova demonstration farm — agricultural machinery", country:"MD / EU", kind:"Procurement", fit:"Industrial hemp", status:"Open", deadline:"5 Oct 2026", buyer:"Czech Development Agency project", summary:"Machinery procurement for a demonstration farm that includes industrial-hemp cultivation. Relevant to equipment and ag-tech suppliers, not a medicinal-cannabis flower tender.", who:"Agricultural machinery, automation and farm-technology suppliers.", source:"ted", url:"https://ted.europa.eu/en/notice/-/detail/615533-2026"}
  ]
};
