(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const PN={profiles:read('radar-partner-profiles',[]),briefs:read('radar-partner-briefs',[]),intros:read('radar-partner-intros',[]),profileStep:1,briefStep:1,profileDraft:{},briefDraft:{}};
const CAP=['Cultivation','Primary processing','EU-GMP processing','Packaging','QP / batch certification','Laboratory / QC','GDP distribution','Import / distribution','Regulatory affairs','Supplier qualification'];
const CREDENTIALS=['Cultivation licence','GACP-aligned quality system','EU-GMP','MIA / manufacturing authorisation','WDA / GDP','Laboratory accreditation','Import / distribution authorisation'];
const VIS={private:{label:'Private',desc:'Only your organisation sees the record. It can still be used internally for readiness and matching.'},network:{label:'Verified network',desc:'Visible only to verified business users in the network.'},anonymous:{label:'Anonymous discovery',desc:'Capabilities can be discovered, but company identity and sensitive fields stay hidden until mutual interest.'},public:{label:'Public',desc:'Institutional profile and selected capabilities may be visible publicly. Sensitive commercial fields remain protected.'}};
const SAMPLE_PROFILES=[
{id:'pn-pt-gmp',demo:true,name:'Illustrative Portuguese GMP processor',country:'PT',site:'Portugal manufacturing site',visibility:'network',capabilities:['EU-GMP processing','Packaging','QP / batch certification'],credentials:[['EU-GMP','DECLARED'],['MIA / manufacturing authorisation','NEEDS VERIFICATION']],markets:['EU','DE','DK','PT'],summary:'European processing and release capability. Illustrative profile; live scope must be verified against the competent register.'},
{id:'pn-ca-cult',demo:true,name:'Illustrative Canadian cultivator',country:'CA',site:'Canadian cultivation site',visibility:'anonymous',capabilities:['Cultivation','Primary processing'],credentials:[['Cultivation licence','DECLARED'],['GACP-aligned quality system','DECLARED']],markets:['CA','EU'],summary:'Cultivation capability seeking qualified European partners. Identity would remain hidden until mutual interest.'},
{id:'pn-de-dist',demo:true,name:'Illustrative German importer/distributor',country:'DE',site:'German distribution site',visibility:'network',capabilities:['GDP distribution','Import / distribution','Regulatory affairs'],credentials:[['WDA / GDP','NEEDS VERIFICATION'],['Import / distribution authorisation','NEEDS VERIFICATION']],markets:['DE'],summary:'Market-access and distribution capability for Germany. Illustrative profile only.'},
{id:'pn-eu-lab',demo:true,name:'Illustrative EU laboratory',country:'EU',site:'EU laboratory site',visibility:'public',capabilities:['Laboratory / QC','Supplier qualification'],credentials:[['Laboratory accreditation','NEEDS VERIFICATION']],markets:['EU','DE','PT','DK','ES'],summary:'Quality-control and specification-review capability. Illustrative profile only.'}
];
const SAMPLE_BRIEFS=[
{id:'pb-gmp-eu',demo:true,title:'Looking for EU-GMP processing and batch-certification partner',owner:'Anonymous licensed operator',country:'EU',target:'EU',need:['EU-GMP processing','QP / batch certification'],visibility:'anonymous',context:'Partner discovery for a European regulated route; no product quantity, price or inventory is disclosed.'},
{id:'pb-de-access',demo:true,title:'Looking for licensed German import / distribution partner',owner:'Anonymous international operator',country:'International',target:'DE',need:['Import / distribution','GDP distribution'],visibility:'network',context:'Market-access partner discovery. Commercial details are shared only after mutual interest.'},
{id:'pb-quality',demo:true,title:'Looking for EU quality / supplier-qualification partner',owner:'Anonymous operator',country:'EU',target:'EU',need:['Supplier qualification','Regulatory affairs'],visibility:'anonymous',context:'Qualification and regulatory capability search, not a product listing.'}
];
function esc(v=''){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function allProfiles(){return [...SAMPLE_PROFILES,...PN.profiles]}
function allBriefs(){return [...SAMPLE_BRIEFS,...PN.briefs]}
function save(){write('radar-partner-profiles',PN.profiles);write('radar-partner-briefs',PN.briefs);write('radar-partner-intros',PN.intros)}
function toast(msg){const r=$('#toastRegion');if(!r)return;const t=document.createElement('div');t.className='toast';t.textContent=msg;r.appendChild(t);setTimeout(()=>t.remove(),2600)}
function isPartner(){return /^#(?:partner|trade)(?:\/|$)/.test(location.hash||'')}
function path(){const raw=(location.hash||'#partner').slice(1).split('/').filter(Boolean);return raw[0]==='trade'?['partner']:raw.length?raw:['partner']}
function enhanceNav(){const s=$('#sidebar');if(s){const old=[...s.querySelectorAll('a[href="#trade"]')];old.forEach(a=>{a.href='#partner';const txt=[...a.childNodes].find(n=>n.nodeType===3);if(txt)txt.textContent='Partner Network';else a.innerHTML=a.innerHTML.replace(/Trade Network|Trade/g,'Partner Network')});if(!s.querySelector('a[href="#partner"]')){const sections=[...s.querySelectorAll('.nav-section')],commerce=sections.find(x=>/Commerce/i.test(x.textContent));if(commerce)commerce.insertAdjacentHTML('beforeend','<a class="nav-item" href="#partner"><span class="nav-icon">⇆</span>Partner Network</a>')}}
const m=$('#mobileNav');if(m){[...m.querySelectorAll('a[href="#trade"]')].forEach(a=>{a.href='#partner';const spans=a.querySelectorAll('span');if(spans[1])spans[1].textContent='Partners'})}}
function tabs(active='home'){return `<div class="pn-tabs">${[['home','Overview'],['directory','Partners'],['briefs','Connection briefs'],['matches','Matches'],['introductions','Introductions'],['qualification','Qualification']].map(([r,l])=>`<a class="pn-tab ${active===r?'active':''}" href="#partner/${r==='home'?'':r}"${active===r?' aria-current="page"':''}>${l}</a>`).join('')}</div>`}
function visibilityPill(v){const x=VIS[v]||VIS.private;return `<span class="pn-pill ${v==='anonymous'?'amber':v==='network'?'blue':v==='private'?'muted':''}">${esc(x.label)}</span>`}
function displayName(p){return p.visibility==='anonymous'?'Anonymous verified partner':p.name}
function profileCard(p){return `<article class="pn-card clickable" data-pn-profile="${esc(p.id)}" role="link" tabindex="0" aria-label="View partner capability: ${esc(displayName(p))}"><div class="pn-meta">${visibilityPill(p.visibility)}<span>${esc(p.country)}</span>${p.demo?'<span>Illustrative</span>':''}</div><h3>${esc(displayName(p))}</h3><p>${esc(p.visibility==='anonymous'?'Identity is protected until mutual interest. '+p.summary:p.summary)}</p><div class="pn-tags">${p.capabilities.slice(0,4).map(x=>`<span class="pn-tag">${esc(x)}</span>`).join('')}</div><div class="pn-card-foot"><small>${p.credentials?.length||0} credential signals · ${p.markets?.length||0} markets</small><span class="pn-pill">View capability →</span></div></article>`}
function briefCard(b){return `<article class="pn-card"><div class="pn-meta">${visibilityPill(b.visibility)}<span>${esc(b.target)}</span>${b.demo?'<span>Illustrative</span>':''}</div><h3>${esc(b.title)}</h3><p>${esc(b.context)}</p><div class="pn-tags">${b.need.map(x=>`<span class="pn-tag">${esc(x)}</span>`).join('')}</div><div class="pn-card-foot"><small>${b.visibility==='anonymous'?'Identity protected':'Verified-network discovery'}</small><button class="btn" data-pn-match-brief="${esc(b.id)}">Find capability matches</button></div></article>`}
function hero(){return `<section class="pn-hero"><div class="pn-hero-top"><div><div class="eyebrow">Partner Network</div><h1>Find the right regulated partner without publishing sensitive commercial data</h1><p>Capability discovery, controlled visibility, mutual introductions, qualification and route readiness. Stock, pricing, quantities and confidential documents are private by default.</p></div><div class="pn-actions"><button class="btn" data-pn-new-profile>Create company/site profile</button><button class="btn primary" data-pn-new-brief>Create connection brief</button></div></div><div class="pn-privacy">${Object.entries(VIS).map(([k,v])=>`<div class="pn-privacy-card"><b>${esc(v.label)}</b><span>${esc(v.desc)}</span></div>`).join('')}</div></section>`}
function summary(){return `<div class="pn-summary"><div class="pn-stat"><span>Partner profiles</span><b>${allProfiles().length}</b><small>Illustrative + browser-local</small></div><div class="pn-stat"><span>Capability briefs</span><b>${allBriefs().length}</b><small>No inventory or pricing required</small></div><div class="pn-stat"><span>Introductions</span><b>${PN.intros.length}</b><small>Mutual-interest workflow</small></div><div class="pn-stat"><span>Privacy modes</span><b>4</b><small>Field exposure is controlled</small></div></div>`}
function home(){return `<div class="pn-shell">${hero()}${summary()}${tabs('home')}<section class="pn-section"><div class="pn-section-head"><div><h2>Capability-first discovery</h2><p>Find organisations by what their sites can do, then verify scope before an introduction.</p></div><a class="section-link" href="#partner/directory">Open directory →</a></div><div class="pn-grid">${allProfiles().slice(0,3).map(profileCard).join('')}</div></section><section class="pn-section"><div class="pn-section-head"><div><h2>Controlled connection briefs</h2><p>Describe the partner capability you need without exposing price, stock or transaction details.</p></div><a class="section-link" href="#partner/briefs">View briefs →</a></div><div class="pn-grid">${allBriefs().slice(0,3).map(briefCard).join('')}</div></section><div class="pn-notice"><b>Privacy principle:</b> the public/verified discovery layer should reveal only enough information to create a relevant introduction. Sensitive commercial information belongs in a private workspace after mutual interest.</div></div>`}
function directory(){return `<div class="pn-shell">${hero()}${tabs('directory')}<div class="pn-section-head"><div><h2>Partner directory</h2><p>Company and site capabilities, with scope and verification status kept separate.</p></div></div><div class="pn-grid">${allProfiles().map(profileCard).join('')}</div></div>`}
function briefs(){return `<div class="pn-shell">${hero()}${tabs('briefs')}<div class="pn-section-head"><div><h2>Connection briefs</h2><p>Need-based partner discovery without publishing inventory, price or purchasing volumes.</p></div><button class="btn primary" data-pn-new-brief>Create brief</button></div><div class="pn-grid">${allBriefs().map(briefCard).join('')}</div></div>`}
function matchesFor(b){return allProfiles().map(p=>{const hits=b.need.filter(n=>p.capabilities.includes(n));const geo=p.markets?.includes(b.target)||p.markets?.includes('EU')||b.target==='EU';const score=Math.round((hits.length/Math.max(1,b.need.length))*80+(geo?20:0));return {p,hits,geo,score}}).filter(x=>x.hits.length).sort((a,b)=>b.score-a.score)}
function matches(id){const brief=allBriefs().find(x=>x.id===id)||allBriefs()[0];const ms=brief?matchesFor(brief):[];return `<div class="pn-shell">${hero()}${tabs('matches')}<div class="pn-section-head"><div><h2>Capability matches</h2><p>${brief?esc(brief.title):'Create a connection brief to generate capability matches.'}</p></div></div>${brief?`<div class="pn-notice"><b>Match score:</b> capability and market relevance only. It does not mean licences, quality scope or route readiness are verified.</div>`:''}<div class="pn-grid two">${ms.length?ms.map(m=>`<article class="pn-card"><div class="pn-match"><div class="pn-match-score"><b>${m.score}%</b><small>capability fit</small></div><div><div class="pn-meta">${visibilityPill(m.p.visibility)}<span>${esc(m.p.country)}</span></div><h3>${esc(displayName(m.p))}</h3><p>${esc(m.p.summary)}</p><div class="pn-match-grid"><div class="pn-match-dim"><b>Capabilities</b><span>${m.hits.length}/${brief.need.length} matched</span></div><div class="pn-match-dim"><b>Market</b><span>${m.geo?'Relevant':'Check required'}</span></div><div class="pn-match-dim"><b>Verification</b><span>Scope review required</span></div></div><div class="pn-card-foot"><small>Commercial details stay private</small><button class="btn primary" data-pn-intro="${esc(m.p.id)}" data-pn-brief="${esc(brief.id)}">Request introduction</button></div></div></div></article>`).join(''):'<div class="pn-empty">No capability matches yet.</div>'}</div></div>`}
function introductions(){return `<div class="pn-shell">${hero()}${tabs('introductions')}<div class="pn-section-head"><div><h2>Introductions</h2><p>Requests stay browser-local in this preview. A real platform would require mutual acceptance before identities or protected fields are revealed.</p></div></div>${PN.intros.length?`<div class="pn-grid two">${PN.intros.map(i=>{const p=allProfiles().find(x=>x.id===i.profileId),b=allBriefs().find(x=>x.id===i.briefId);return `<div class="pn-card"><div class="pn-meta"><span class="pn-pill blue">${esc(i.status)}</span><span>${new Date(i.at).toLocaleDateString()}</span></div><h3>${esc(b?.title||'Partner introduction')}</h3><p>${esc(p?displayName(p):'Partner')}</p><div class="pn-row"><span>Identity</span><b>Protected until mutual acceptance</b></div><div class="pn-row"><span>Commercial details</span><b>Private</b></div><div class="pn-row"><span>Next step</span><b>Qualification readiness</b></div></div>`}).join('')}</div>`:'<div class="pn-empty">No introduction requests yet. Request one from a capability match.</div>'}</div>`}
function qualification(){const p=PN.profiles[0]||allProfiles()[0];return `<div class="pn-shell">${hero()}${tabs('qualification')}<div class="pn-section-head"><div><h2>Qualification workspace</h2><p>Keep declarations, verification and blockers separate. A green company-level badge never substitutes for site/activity scope.</p></div></div><div class="pn-grid two"><div class="pn-card"><div class="pn-meta">${visibilityPill(p.visibility)}<span>${esc(p.country)}</span></div><h3>${esc(displayName(p))}</h3><p>${esc(p.site||'Site not disclosed')}</p><div class="pn-qual"><div class="pn-qual-row"><span class="pn-qual-icon">1</span><div><b>Legal entity & site</b><small>Entity and relevant operating site.</small></div><span class="pn-status ${p.name?'declared':'verify'}">${p.name?'DECLARED':'NEEDS VERIFICATION'}</span></div><div class="pn-qual-row"><span class="pn-qual-icon">2</span><div><b>Licence / authorisation scope</b><small>Must match the actual site and activity.</small></div><span class="pn-status verify">NEEDS VERIFICATION</span></div><div class="pn-qual-row"><span class="pn-qual-icon">3</span><div><b>Quality credentials</b><small>Credential existence and scope are separate.</small></div><span class="pn-status declared">DECLARED</span></div><div class="pn-qual-row"><span class="pn-qual-icon">4</span><div><b>Target-market applicability</b><small>Review per route/use case.</small></div><span class="pn-status verify">NEEDS VERIFICATION</span></div></div></div><div class="pn-card"><h3>Verification states</h3><div class="pn-row"><span>VERIFIED</span><b>Evidence reviewed for entity/site/scope</b></div><div class="pn-row"><span>DECLARED</span><b>Counterparty claim, not yet verified</b></div><div class="pn-row"><span>NEEDS VERIFICATION</span><b>Evidence or applicability incomplete</b></div><div class="pn-row"><span>NOT APPLICABLE</span><b>Reason documented</b></div><div class="pn-row"><span>BLOCKED</span><b>Required condition not satisfied</b></div><div class="pn-notice" style="margin-top:12px"><b>Hard blockers are not averaged away.</b> Capability fit and qualification readiness are displayed separately.</div></div></div></div>`}
function profile(id){const p=allProfiles().find(x=>x.id===id);if(!p)return directory();return `<div class="pn-shell">${hero()}${tabs('directory')}<section class="pn-card"><div class="pn-meta">${visibilityPill(p.visibility)}<span>${esc(p.country)}</span>${p.demo?'<span>Illustrative</span>':''}</div><h1 style="font-size:26px;margin:10px 0 6px">${esc(displayName(p))}</h1><p>${esc(p.summary)}</p><div class="pn-grid two" style="margin-top:16px"><div><div class="pn-row"><span>Site</span><b>${esc(p.visibility==='anonymous'?'Protected until mutual interest':p.site||'—')}</b></div><div class="pn-row"><span>Markets</span><b>${esc((p.markets||[]).join(' · '))}</b></div><div class="pn-row"><span>Visibility</span><b>${esc(VIS[p.visibility]?.label||'Private')}</b></div></div><div><h3>Capabilities</h3><div class="pn-tags">${p.capabilities.map(x=>`<span class="pn-tag">${esc(x)}</span>`).join('')}</div></div></div><section style="margin-top:20px"><div class="pn-section-head"><div><h2>Credentials</h2><p>Claim and verification state are deliberately separate.</p></div></div>${(p.credentials||[]).map(([c,s])=>`<div class="pn-row"><span>${esc(c)}</span><b class="pn-status ${s==='VERIFIED'?'verified':s==='DECLARED'?'declared':'verify'}">${esc(s)}</b></div>`).join('')}</section><div class="pn-card-foot"><small>Protected information is not exposed in discovery.</small><button class="btn primary" data-pn-intro="${esc(p.id)}">Request introduction</button></div></section></div>`}
function profileWizard(){const d=PN.profileDraft,s=PN.profileStep,total=4;let body='';if(s===1)body=`<div class="pn-form"><div class="pn-form-grid"><label>Organisation name<input data-pnd="name" value="${esc(d.name||'')}" placeholder="Company name"></label><label>Country<select data-pnd="country"><option value="">Select…</option>${['PT','DE','DK','ES','UK','CA','AU','NL','CZ','Other'].map(x=>`<option ${d.country===x?'selected':''}>${x}</option>`).join('')}</select></label></div><label>Site / facility name<input data-pnd="site" value="${esc(d.site||'')}" placeholder="The site whose capabilities you are describing"></label><div class="pn-form-help">Create a reusable site profile once; future connection briefs can reference it instead of re-entering company information.</div></div>`;
if(s===2)body=`<div class="pn-form"><div class="pn-checks">${CAP.map(x=>`<label class="pn-check"><input type="checkbox" data-pncap="${esc(x)}" ${(d.capabilities||[]).includes(x)?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div></div>`;
if(s===3)body=`<div class="pn-form"><div class="pn-checks">${CREDENTIALS.map(x=>`<label class="pn-check"><input type="checkbox" data-pncred="${esc(x)}" ${(d.credentials||[]).includes(x)?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div><div class="pn-notice"><b>Important:</b> selected credentials are saved as DECLARED. They do not become VERIFIED until evidence is reviewed for the exact entity, site and activity scope.</div></div>`;
if(s===4)body=`<div class="pn-form"><h3>Who should be able to discover this site?</h3><div class="pn-visibility">${Object.entries(VIS).map(([k,v])=>`<label class="pn-choice"><input type="radio" name="pnvis" data-pnvis="${k}" ${(d.visibility||'anonymous')===k?'checked':''}><div><b>${esc(v.label)}</b><small>${esc(v.desc)}</small></div></label>`).join('')}</div><label>Short capability summary<textarea data-pnd="summary" placeholder="Describe the site's role and capabilities without sensitive commercial details.">${esc(d.summary||'')}</textarea></label></div>`;
return `<div class="pn-shell">${tabs('directory')}<div class="pn-wizard"><div class="pn-progress"><span style="width:${s/total*100}%"></span></div><div class="pn-step-kicker">Company / site profile · Step ${s} of ${total}</div><h2>${['Identity & site','Capabilities','Credentials','Privacy & review'][s-1]}</h2><p class="lead">${['Create the reusable organisation/site identity.','Select what this site can actually do.','Declare credentials; verification remains separate.','Choose discovery visibility before saving.'][s-1]}</p>${body}<div class="pn-wizard-nav"><button class="btn" data-pn-profile-back ${s===1?'disabled':''}>← Back</button><button class="btn primary" data-pn-profile-next>${s===total?'Save profile':'Continue →'}</button></div></div></div>`}
function briefWizard(){const d=PN.briefDraft,s=PN.briefStep,total=3;let body='';if(s===1)body=`<div class="pn-form"><label>What capability are you looking for?<select data-pnb="need"><option value="">Select…</option>${CAP.map(x=>`<option ${d.need===x?'selected':''}>${esc(x)}</option>`).join('')}</select></label><label>Brief title<input data-pnb="title" value="${esc(d.title||'')}" placeholder="e.g. Looking for EU-GMP processing partner"></label><div class="pn-form-help">Do not include price, inventory, batch quantity or confidential transaction data. Those belong in a private workspace after mutual interest.</div></div>`;
if(s===2)body=`<div class="pn-form-grid"><label>Your region / country<select data-pnb="country"><option value="">Select…</option>${['EU','PT','DE','DK','ES','UK','CA','AU','International'].map(x=>`<option ${d.country===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Target market<select data-pnb="target"><option value="">Select…</option>${['EU','PT','DE','DK','ES','UK','CA','AU'].map(x=>`<option ${d.target===x?'selected':''}>${x}</option>`).join('')}</select></label></div>`;
if(s===3)body=`<div class="pn-form"><h3>Discovery visibility</h3><div class="pn-visibility">${[['private','Private'],['network','Verified network'],['anonymous','Anonymous discovery']].map(([k])=>`<label class="pn-choice"><input type="radio" name="pnbvis" data-pnbvis="${k}" ${(d.visibility||'anonymous')===k?'checked':''}><div><b>${esc(VIS[k].label)}</b><small>${esc(VIS[k].desc)}</small></div></label>`).join('')}</div><label>Context<textarea data-pnb="context" placeholder="Explain the partnership need without sensitive commercial terms.">${esc(d.context||'')}</textarea></label></div>`;
return `<div class="pn-shell">${tabs('briefs')}<div class="pn-wizard"><div class="pn-progress"><span style="width:${s/total*100}%"></span></div><div class="pn-step-kicker">Connection brief · Step ${s} of ${total}</div><h2>${['Partner capability','Geography','Privacy & review'][s-1]}</h2><p class="lead">Describe enough for relevant partners to find you, without exposing confidential commercial information.</p>${body}<div class="pn-wizard-nav"><button class="btn" data-pn-brief-back ${s===1?'disabled':''}>← Back</button><button class="btn primary" data-pn-brief-next>${s===total?'Save brief':'Continue →'}</button></div></div></div>`}
function render(){if(!isPartner()){enhanceNav();return}enhanceNav();const p=path(),main=$('#main');if(!main)return;let html='';if(p[1]==='directory')html=directory();else if(p[1]==='briefs')html=briefs();else if(p[1]==='matches')html=matches(p[2]);else if(p[1]==='introductions')html=introductions();else if(p[1]==='qualification')html=qualification();else if(p[1]==='profile')html=profile(p[2]);else if(p[1]==='new-profile')html=profileWizard();else if(p[1]==='new-brief')html=briefWizard();else html=home();main.innerHTML=html;window.scrollTo({top:0,behavior:'instant'})}
function collectProfileDraft(){$$('[data-pnd]').forEach(el=>PN.profileDraft[el.dataset.pnd]=el.value);PN.profileDraft.capabilities=$$('[data-pncap]:checked').map(x=>x.dataset.pncap);PN.profileDraft.credentials=$$('[data-pncred]:checked').map(x=>x.dataset.pncred);const v=$('[data-pnvis]:checked');if(v)PN.profileDraft.visibility=v.dataset.pnvis}
function collectBriefDraft(){$$('[data-pnb]').forEach(el=>PN.briefDraft[el.dataset.pnb]=el.value);const v=$('[data-pnbvis]:checked');if(v)PN.briefDraft.visibility=v.dataset.pnbvis}
function saveProfile(){collectProfileDraft();const d=PN.profileDraft;if(!d.name||!d.country){toast('Add organisation name and country first');PN.profileStep=1;render();return}const id=`partner-${Date.now()}`;PN.profiles.unshift({id,demo:false,name:d.name,country:d.country,site:d.site||'Site not specified',visibility:d.visibility||'anonymous',capabilities:d.capabilities||[],credentials:(d.credentials||[]).map(x=>[x,'DECLARED']),markets:d.country==='EU'?['EU']:[d.country,'EU'],summary:d.summary||'Browser-local partner profile.'});PN.profileDraft={};PN.profileStep=1;save();location.hash=`partner/profile/${id}`;toast('Partner profile saved in this browser')}
function saveBrief(){collectBriefDraft();const d=PN.briefDraft;if(!d.need){toast('Select a partner capability first');PN.briefStep=1;render();return}const id=`brief-${Date.now()}`;PN.briefs.unshift({id,demo:false,title:d.title||`Looking for ${d.need} partner`,owner:'Browser-local organisation',country:d.country||'International',target:d.target||'EU',need:[d.need],visibility:d.visibility||'anonymous',context:d.context||'Capability-based partner discovery. Sensitive commercial information remains private.'});PN.briefDraft={};PN.briefStep=1;save();location.hash=`partner/matches/${id}`;toast('Connection brief saved')}
document.addEventListener('keydown',e=>{const p=e.target.closest('[data-pn-profile]');if(p&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.hash=`partner/profile/${p.dataset.pnProfile}`}});
document.addEventListener('click',e=>{const p=e.target.closest('[data-pn-profile]');if(p){location.hash=`partner/profile/${p.dataset.pnProfile}`;return}if(e.target.closest('[data-pn-new-profile]')){PN.profileStep=1;PN.profileDraft={};location.hash='partner/new-profile';return}if(e.target.closest('[data-pn-new-brief]')){PN.briefStep=1;PN.briefDraft={};location.hash='partner/new-brief';return}if(e.target.closest('[data-pn-profile-next]')){collectProfileDraft();if(PN.profileStep<4){PN.profileStep++;render()}else saveProfile();return}if(e.target.closest('[data-pn-profile-back]')){collectProfileDraft();PN.profileStep=Math.max(1,PN.profileStep-1);render();return}if(e.target.closest('[data-pn-brief-next]')){collectBriefDraft();if(PN.briefStep<3){PN.briefStep++;render()}else saveBrief();return}if(e.target.closest('[data-pn-brief-back]')){collectBriefDraft();PN.briefStep=Math.max(1,PN.briefStep-1);render();return}const mb=e.target.closest('[data-pn-match-brief]');if(mb){location.hash=`partner/matches/${mb.dataset.pnMatchBrief}`;return}const intro=e.target.closest('[data-pn-intro]');if(intro){const rec={id:`intro-${Date.now()}`,profileId:intro.dataset.pnIntro,briefId:intro.dataset.pnBrief||'',status:'REQUESTED',at:new Date().toISOString()};PN.intros.unshift(rec);save();toast('Introduction request created — identity remains protected until mutual acceptance');location.hash='partner/introductions';return}});
window.addEventListener('hashchange',()=>setTimeout(render,0));
setTimeout(()=>{enhanceNav();render()},0);
})();
